name: ci-api-test

on:
  pull_request:
    branches:
      - main
jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: execute maven
        run:  mvn clean test '-Dsuite=contract' '-Denv=dev'
  functional-test:
    needs: [contract-test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: execute maven
        run:  mvn clean test '-Dsuite=regression' '-Denv=dev'
  integration-test:
    needs: [contract-test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: execute maven
        run: mvn clean test '-Dsuite=integration' '-Denv=dev'